name: Build Auth Workflow

inputs:
  target_module:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: input test
      run: echo ${{ inputs.target_module }}
    - name: Gradle Build (auth)
      run: |
        cd ${{ inputs.target_module }}
        ./gradlew build