spring:
  profiles:
    active: local # default profile
    group:
      local:
        - common
      unit-test:
        - common
      develop:
        - common

---
# 공통
spring:
  config:
    activate:
      on-profile: common
server:
  port: 3000

---
# local
service:
  jwt:
    secret-key: "2cb6363001584512e547b1e327a0404dd48ba9e2452b277c0d0bb4aec3024aff5a82fe17c50e5ed573223b7139cd476252d6082673c33fe1677be106d5223252"