name: github-actions-develop
on:
  pull_request:
    branches:
      - develop

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      module: ${{ steps.detect.outputs.module }}
    steps:
      - name: checkout project sources
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - run: echo "setting before build and test is finished"