name: build-test

on:
  push:
    branches:
      - features/github-actions

env:
  PROJECT_ROOT: ${{ github.action_path }}/../../

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Gradle Build - auth
        run: |
          cd auth
          ./gradlew build

      - name: Gradle Build - user
        run: |
          cd user
          ./gradlew build

      - name: Gradle Build - content
        run: |
          cd content
          ./gradlew build

      - name: Gradle Build - gateway
        run: |
          cd gateway
          ./gradlew build