name: Pull Request Workflow (develop)

on:
  pull_request:
    branches:
      - develop

jobs:
  use-github-actions-auth:
    uses: ./.github/github-actions-auth.yaml
    with:
      target_module: "auth"