name: build-test

on:
  push:
    branches:
      - features/github-actions

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build
        run: |
          cd auth
          ./gradlew build
            

