name: Pull Request Workflow (develop)

on:
  pull_request:
    branches:
      - develop

jobs:
  build_modules:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - name: auth build
        uses: ./.github/actions/build
        with:
          target: auth
      - name: content build
        uses: ./.github/actions/build
        with:
          target: content
      - name: user build
        uses: ./.github/actions/build
        with:
          target: user
      - name: gateway build
        uses: ./.github/actions/build
        with:
          target: gateway