name: Pull Request Workflow (develop)

on:
  pull_request:
    branches:
      - develop

jobs:
  build_modules:
    runs-on: ubuntu-latest
    steps:
      - name: My first step - check out repository
        uses: actions/checkout@v4
      - name: auth build
        uses: ./.github/actions/build
        with:
          target: auth